version: '3'

services:
  kojid:
    build: kojid
    privileged: true
    volumes:
      - "./kojid/config:/etc/kojid:ro"
      # - "/mnt/koji:/mnt/koji:z"
    extra_hosts:
      - "openkoji.iscas.ac.cn:192.168.6.177"
    restart: always